const SHELL_CACHE='map-app-shell-v2';
const PARCEL_CACHE='map-app-parcels-v2';
const APP_SHELL=['./','./index.html','./parcel-data/index.json','./offline-controls.js'];
self.addEventListener('install',event=>event.waitUntil(caches.open(SHELL_CACHE).then(cache=>cache.addAll(APP_SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith('map-app-')&&key!==SHELL_CACHE&&key!==PARCEL_CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
function addControls(response){return response.text().then(html=>new Response(html.replace('</body>','<script src="offline-controls.js"></script></body>'),{headers:{'Content-Type':'text/html; charset=utf-8'}}));}
function send(client,message){if(client&&client.postMessage)client.postMessage(message);}
self.addEventListener('fetch',event=>{const request=event.request,url=new URL(request.url);if(request.method!=='GET'||url.origin!==self.location.origin)return;const isPage=request.mode==='navigate'||url.pathname.endsWith('/index.html')||url.pathname.endsWith('/mapapp/');if(isPage){event.respondWith(caches.match(request).then(cached=>cached||fetch(request).then(response=>{if(response.ok)caches.open(SHELL_CACHE).then(cache=>cache.put(request,response.clone()));return response}).then(addControls)));return}const parcel=url.pathname.includes('/parcel-data/');event.respondWith(caches.open(parcel?PARCEL_CACHE:SHELL_CACHE).then(cache=>cache.match(request).then(cached=>cached||fetch(request).then(response=>{if(response.ok)cache.put(request,response.clone());return response}))));});
self.addEventListener('message',event=>{const data=event.data||{},client=event.source;if(data.type==='clear-parcels'){event.waitUntil(caches.delete(PARCEL_CACHE).then(()=>send(client,{type:'cleared'})));return}if(data.type!=='download-parcels'||!Array.isArray(data.urls))return;event.waitUntil(caches.open(PARCEL_CACHE).then(async cache=>{let saved=0;for(const url of data.urls){try{const response=await fetch(url);if(response.ok){await cache.put(url,response);saved++}}catch(_){ }send(client,{type:'progress',saved,total:data.urls.length})}send(client,{type:'complete',saved,total:data.urls.length})}));});
